sudo: required
services:
  - docker

before_install:
  - docker build -t akhilankireddy/docker-react -f Dockerfile.dev .

script:
  - docker run akhilankireddy/docker-react npm run test -- --coverage
